[package]
name = "rustapp"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
eframe = "0.27.2"
http = "1.1.0"
serde_json = "1.0.118"
ureq = { version = "2.9.7", features = ["json"] }
